### ISSUE TITLE
Problems with linked images in resulting pdf file

### ISSUE THREAD

**Issue by mariusandersen** [BlueHatbRit/mdpdf#14]
I was testing with images like described here https://docs.gitlab.com/ee/user/markdown.html#images

I have an md file with an img/markdown_logo.png

md file:
`![alt text](img/markdown_logo.png)`
Opening md file in Typora looks perfect.

resulting html file:
`<img src="file://C:\test\img\markdown_logo.png" alt="alt text">`
Opening html file in Chrome - it lost it's centering of the image (but that can be fixed via .css)

PDF file however loses the image and instead just displays "alt text".

Would like the html-to-pdf conversion to embed images. Possible?

**Comment by BlueHatbRit** [comment]
I use relative image links all the time and haven't had a problem so far. Try:

`![alt text](./img/markdown_logo.png)`

Which contains a proceeding `./` to define the directory :)

**Comment by BlueHatbRit** [comment]
I'm assuming this issue has been resolved, feel free to re-open it if you're still having the same problem.

**Comment by mariusandersen** [comment]
Hello. I retried with your suggestion. So
`![alt text](./img/markdown_logo.png)`
Became in HTML 
`<img src="file://C:\git\Test\Documentation\img\markdown_logo.png" alt="alt text">`
Open HTML in Chrome, looks OK (except not centered like the MD file default does)
PDF file unfortunatly still just showing a box with "alt text".

How does the img tag in the html file look in your case?

**Comment by BlueHatbRit** [comment]
Hi @mariusandersen, this sounds really frustrating, it looks like there's something going on with Phantomjs retreiving the image.

I'm at work at the moment and thus don't have access to Windows which seems to be where the issue is so I'll have to take a look this evening. Thanks for debugging it in the HTML, that's a huge help. Sadly it's really hard to test PDF content but I'm working on it.

I'll take a look for you this evening and get back to you on this. I have a hunch it's to do with the default assets directory I've selected in the mdpdf code.

**Comment by BlueHatbRit** [comment]
Found the issue and I'm resolving it over the next few hours @mariusandersen :)

**Comment by BlueHatbRit** [comment]
@mariusandersen 1.3.2 has been published fixing this issue on Windows! I would recommend always including the `./` though as it's just good practice :)

**Comment by mariusandersen** [comment]
Hello.

I updated to 1.3.2 and I still seem to get the issue unfortunatly.

md file:
`![alt text](./img/markdown_logo.png)`
(also tried without './')

resulting html file:
`<img src="file:///C:/test/img/markdown_logo.png" alt="alt text">`
Opening HTML file in Chrome - Error showing "alt text" box (assuming this is because the Windows slashes on file path is supposed to be the other way around).

resulting pdf file:
Error showing "alt text" box

**Comment by BlueHatbRit** [comment]
@mariusandersen I got an email about a new comment you'd left saying this was still an issue, but the comment doesn't seem to be here. Is this still an issue for you?

**Comment by Stranger-Ok** [comment]
I don't know if issue is the same, but if we specify image path in header file, in pdf image not working.
add to header 
<center>
	<div class="divHeaderRight">
		<img src="./logo.png" height="25" width="50"/>
and in pdf image block is empty.

**Comment by mariusandersen** [comment]
Hello.

Thank you for taking your time to fix this issue.

I updated to 1.3.2 and I now seem to get a different issue unfortunately.

md file:
![alt text](./img/markdown_logo.png)
(also tried without './')

resulting html file:
<img src="file:///C:/img/markdown_logo.png" alt="alt text">
Opening HTML file in Chrome - Error showing "alt text" box.

resulting pdf file:
Error showing "alt text" box

The reason for this is because I call the .md file from a remote folder.
I am in folder C: then I write "mdpdf test/markdown.md".
My img folder is located on _C:/test/img/markdown.png_ but as you see in the file path in the html it is looking for it in _C:/img/markdown.png_

**Comment by BlueHatbRit** [comment]
@mariusandersen Ah that's it! I should have asked where you were calling it from, this makes things much easier to sort. So it seems that image paths are not relative to the MD file directory, but to the directory the process is being started from.

Thanks, I can now go in and correct this and you can expect to see an update sometime today or early tomorrow morning. I'm really sorry for the inconvenience!

**Comment by BlueHatbRit** [comment]
@Stranger-Ok, are you calling mdpdf from the same directory as the markdown file (IE: are the image paths relative to where you are when you call the mdpdf command)? If so, then this is the same issue and should be resolved within the next 24hours in a 1.3.4 update.

**Comment by Stranger-Ok** [comment]
@BlueHatbRit , no, but I also try to use relative path from where I call mdpdf and it still not working.

**Comment by BlueHatbRit** [comment]
@Stranger-Ok alright, I'll fix this later today and we'll see if your issue persists. Can you tell me the following:

* What directory are you running the `mdpdf` command from?
* What directory is your markdown file in.
* What code are you using for the image.
* What directory is your image in?

**Comment by Stranger-Ok** [comment]
@BlueHatbRit simple structure, in root we have "gruntfile.js"  witch has a task to run mdpdf .
Inside root folder we have "documents" folder, where "readme.md", "readme_header.html", "readme.css" are stored.
Inside "documents" folder we have "images" folder where "logo.png" is stored.
I add to "readme_header.html" 
`<img src="./documents/images/logo.png" height="25" width="50"/>`

After converting to pdf image not exists. In html file image is exists and relative path not changed.

**Comment by BlueHatbRit** [comment]
@Stranger-Ok I'll re-build form that later today to track down the issue. I don't suppose you can give me the code from the gruntfile you're using so I can make sure I'm testing with the exact code you're using?

**Comment by Stranger-Ok** [comment]
@BlueHatbRit Here it is small example. To run converting just execute the command: "grunt convertMdToPdfTask" . Don't forget to execute "npm install -g grunt-cli", "npm install".

https://drive.google.com/file/d/0B5ZtuDBysaLJWE93anFURU4xbHc/view?usp=sharing

**Comment by BlueHatbRit** [comment]
@Stranger-Ok oh that's fantastic thank you for providing a demo project for it! I'll pull that down when I get home and can look into this overall issue.

**Comment by BlueHatbRit** [comment]
@mariusandersen I have implemented a fix for this issue now, it's currently going through the CI server and I hope to publish it within the hour (assuming the builds trigger properly). The issue seemed to be that we were not resolving images relative to the markdown file, but relative to the process.

@Stranger-Ok I've had a look at the code you provided (thanks again) and it seems to be working fine under the change described above. I did however notice you had an error in your markdown file which could also have been causing your issue. Your directory structure was this:

-- Doc
---- readme.md
---- img/
------ logo.png

Within your markdown file you had the following `![logo](./Doc/img/logo.png)` which would be an incorrect path as the markdown file is already within the Doc directory. After changing this to `![logo](./img/logo.png)` and running it under the new changes made (described in #17 and above) all seems well!

Looks like this latest update is going to resolve the issue and it should be out soon.

**Comment by BlueHatbRit** [comment]
The fix has been shipped as mdpdf 1.3.3, feel free to give it a test drive!

**Comment by mariusandersen** [comment]
It works perfectly now. Appreciate the time and effort!

**Comment by BlueHatbRit** [comment]
@mariusandersen thanks for confirming it and no worries, I'm sorry such a simple thing was an issue for so long. Thanks for your help to resolve it.

**Comment by Stranger-Ok** [comment]
@BlueHatbRit Hello, sorry for late reply.Images in md file works correctly, thanks for work. 
But in header image is still not showing. I watch on code and it seems because function "qualifyImgSources" is called only for content (md file), may be we should add this call for footer and header html too?

**Comment by Stranger-Ok** [comment]
@BlueHatbRit Also I found another issue, that's also related to images resolving.
If I run mdpfd from command line, converting completes successfully, but if I call "mdpdf.convert(options)" from code. I'm getting an exception "TypeError: Path must be a string. Received undefined" on resolving image path to URL. Can you try to do the same?

**Comment by BlueHatbRit** [comment]
@Stranger-Ok I'm going to open a new ticket for the header issue, can you open one for this second issue you've identified?

**Comment by Stranger-Ok** [comment]
@BlueHatbRit  Ok.
